# Generated by Django 5.1.2 on 2024-10-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='estb_date',
            field=models.PositiveIntegerField(),
        ),
    ]
