# Generated by Django 5.1.2 on 2024-10-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_place_estb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemembers',
            name='level',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='places/logo/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='office_location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
