# Generated by Django 5.1.2 on 2024-10-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_executivemembers_level_alter_place_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='ExtraPage',
        ),
    ]
