# Generated by Django 5.1.2 on 2024-10-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_page_extrapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('municipality', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='site_info/')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
