# Generated by Django 5.1.2 on 2024-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='ward_no',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
