# Generated by Django 5.1.2 on 2024-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sender_name', models.CharField(max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=16)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
