# Generated by Django 5.1.2 on 2024-10-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_importantcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantcontact',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
