# Generated by Django 5.1.2 on 2024-10-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_importantcontact_display_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantcontact',
            old_name='service',
            new_name='service_provider',
        ),
        migrations.AddField(
            model_name='importantcontact',
            name='service_type',
            field=models.CharField(choices=[('Ambulance', 'Ambulance'), ('Hospital', 'Hospital'), ('Nepal Police', 'Nepal Police'), ('Electricity Authority', 'Electricity Authority'), ('Water Supply', 'Water Supply'), ('LPG Gas', 'LPG Gas'), ('Others', 'Others')], default='Ambulance', max_length=64),
            preserve_default=False,
        ),
    ]
