# Generated by Django 5.1.2 on 2024-11-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_service_importantcontact_service_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group_name', models.CharField(max_length=64)),
                ('group_image', models.ImageField(upload_to='cultural_groups/')),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_name', models.CharField(max_length=64)),
                ('occurrence', models.CharField(blank=True, max_length=64, null=True)),
                ('event_image', models.ImageField(upload_to='cultural_events/')),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cultural_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.culturalgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
