# Generated by Django 5.1.2 on 2024-11-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_culturalgroup_culturalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
