# Generated by Django 5.1.2 on 2024-12-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_culturalevent_event_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culturalevent',
            old_name='event_slug',
            new_name='slug',
        ),
    ]
