# Generated by Django 5.1.2 on 2024-12-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_event_slug_culturalevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_email_alt',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_mobile_alt',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
