# Generated by Django 5.1.2 on 2024-12-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_siteinfo_contact_email_siteinfo_contact_email_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='contact_mobile',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='contact_mobile_alt',
            new_name='contact_number_alt',
        ),
    ]
